name: R-CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt install libgit2-dev
      - name: a
        run: |
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
      - name: b
        run: |
          sudo apt-get install libcurl4-openssl-dev libssl-dev r-cran-devtools libgit2-dev
      - name: b
        run: |
          sudo apt install build-essential libcurl4-gnutls-dev libxml2-dev libssl-dev
      - name: Install devtools
        run: |
          Rscript -e "install.packages('pkgdown')"
          Rscript -e "install.packages('devtools')"

      - name: install dependencies from github
        run: |
          Rscript -e "devtools::install_github("LabAsim/lavaanPlot", force = T)"
      - name: Install test dependencies
        run: |
          Rscript -e "install.packages('testthat')"
      - name: Run tests
        run: |
          Rscript -e "library(testthat);library(testthat);library(lavaan);library(lavaanPlot); test_dir('tests')"
