name: R-CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev
          sudo apt-get install libcurl4-openssl-dev libssl-dev r-cran-devtools libgit2-dev


      - name: Install devtools
        run: |
           Rscript -e "install.packages('devtools')"


      - name: Install test dependencies
        run: |
          Rscript -e "install.packages('testthat')"
      - name: Run tests
        run: |
          Rscript -e "library(testthat); test_dir('tests')"
